import nodemailer from "nodemailer";

interface SendEmailParams {
  to: string;
  subject: string;
  html: string;
}

let transporter: ReturnType<typeof nodemailer.createTransport> | null = null;

function getTransporter() {
  if (!process.env.GMAIL_USER || !process.env.GMAIL_PASS) return null;
  if (!transporter) {
    transporter = nodemailer.createTransport({
      service: "gmail",
      auth: { user: process.env.GMAIL_USER, pass: process.env.GMAIL_PASS }
    });
  }
  return transporter;
}

export async function sendEmail({ to, subject, html }: SendEmailParams): Promise<void> {
  const t = getTransporter();
  if (!t) {
    console.log("EMAIL_SKIP: GMAIL credentials not configured");
    return;
  }
  try {
    const info = await t.sendMail({
      from: `"NRI Trust Advisory" <${process.env.GMAIL_USER}>`,
      to, subject, html
    });
    console.log("EMAIL_SENT:", info.messageId);
  } catch (err) {
    console.error("EMAIL_FAILED:", err);
    throw err;
  }
}

// ─── USER CONFIRMATION EMAIL ─────────────────────────────────────────────────

export function getUserTemplate(name: string, persona: string, urgency: string, summary: string, pdfUrl: string): string {
  const zoneColors: Record<string, string> = { GREEN: '#22c55e', ORANGE: '#f97316', RED: '#ef4444' };
  const zoneColor = zoneColors[persona] || '#CFA052';

  const summaryHtml = summary
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/---/g, '<hr style="border:none;border-top:1px solid #eee;margin:16px 0">')
    .replace(/🔴/g, '<span style="color:#ef4444">🔴</span>')
    .replace(/🟠/g, '<span style="color:#f97316">🟠</span>')
    .replace(/🟡/g, '<span style="color:#eab308">🟡</span>')
    .replace(/◉/g, '<span style="color:#ef4444">◉</span>')
    .replace(/\n\n/g, '</p><p style="margin:0 0 12px">')
    .replace(/\n/g, '<br>');

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F5F5F0;font-family:Georgia,serif">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F5F0;padding:32px 16px">
  <tr><td align="center">
    <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.08)">

      <!-- Header -->
      <tr><td style="background:#0A0F0D;padding:28px 36px">
        <table width="100%"><tr>
          <td>
            <div style="color:#CFA052;font-size:22px;font-weight:bold;letter-spacing:2px;font-family:Georgia,serif">NRI TRUST</div>
            <div style="color:#888;font-size:10px;letter-spacing:3px;margin-top:4px;font-family:Arial,sans-serif">CONFIDENTIAL ADVISORY BRIEF</div>
          </td>
          <td align="right">
            <div style="background:${zoneColor};color:#fff;font-size:9px;font-weight:bold;padding:6px 14px;border-radius:4px;letter-spacing:1px;font-family:Arial,sans-serif">${persona} ZONE &nbsp;·&nbsp; ${urgency}</div>
          </td>
        </tr></table>
      </td></tr>

      <!-- Greeting -->
      <tr><td style="padding:28px 36px 0">
        <p style="font-size:16px;color:#1A1A1A;margin:0 0 8px">Dear ${name},</p>
        <p style="font-size:13px;color:#555;line-height:1.7;margin:0 0 20px">
          Your NRI Family Protection Assessment has been processed. Below is your confidential advisory brief, generated by our intelligence engine based on your specific family situation.
        </p>
      </td></tr>

      <!-- Report body -->
      <tr><td style="padding:0 36px 28px">
        <div style="border-left:3px solid #CFA052;padding:20px 24px;background:#FDFCFB;border-radius:0 6px 6px 0;font-size:13px;color:#333;line-height:1.8">
          <p style="margin:0 0 12px">${summaryHtml}</p>
        </div>
      </td></tr>

      <!-- PDF CTA -->
      ${pdfUrl && pdfUrl !== '#' ? `
      <tr><td style="padding:0 36px 28px;text-align:center">
        <a href="${pdfUrl}" style="display:inline-block;background:#CFA052;color:#0A0F0D;font-weight:bold;font-size:12px;letter-spacing:1px;padding:14px 32px;border-radius:4px;text-decoration:none;font-family:Arial,sans-serif">DOWNLOAD YOUR ADVISORY BRIEF (PDF)</a>
        <p style="font-size:11px;color:#999;margin-top:10px;font-family:Arial,sans-serif">Your personalised PDF report is ready to download</p>
      </td></tr>` : ''}

      <!-- Next step -->
      <tr><td style="padding:0 36px 28px">
        <div style="background:#0A0F0D;border-radius:6px;padding:20px 24px">
          <div style="color:#CFA052;font-weight:bold;font-size:12px;letter-spacing:1px;margin-bottom:8px;font-family:Arial,sans-serif">YOUR NEXT STEP</div>
          <div style="color:#ccc;font-size:13px;line-height:1.7">Your senior advisor is reviewing these findings and will contact you within <strong style="color:#CFA052">4 hours</strong> to schedule your complimentary 30-minute Strategy Session.</div>
        </div>
      </td></tr>

      <!-- Footer -->
      <tr><td style="background:#F5F5F0;padding:20px 36px;text-align:center">
        <div style="color:#999;font-size:10px;line-height:1.6;font-family:Arial,sans-serif">
          NRI Trust Advisory &nbsp;·&nbsp; nri-trust.vercel.app<br>
          This communication is strictly confidential and intended solely for ${name}.<br>
          <span style="color:#ccc">© 2025 NRI Trust. All rights reserved.</span>
        </div>
      </td></tr>

    </table>
  </td></tr>
</table>
</body>
</html>`;
}

// ─── ADVISOR NOTIFICATION EMAIL ──────────────────────────────────────────────

export function getAdvisorTemplate(data: {
  persona: string; urgency: string; name: string; email: string;
  country: string; flags: string[]; summary: string; score: number;
}): string {
  const urgencyColors: Record<string, string> = { CRITICAL: '#ef4444', MODERATE: '#f97316', STABLE: '#22c55e' };
  const urgencyColor = urgencyColors[data.urgency] || '#CFA052';

  const flagsHtml = data.flags.length > 0
    ? data.flags.map(f => `<li style="color:#ef4444;padding:2px 0">${f.replace('FLAG_', '').replace(/_/g, ' ')}</li>`).join('')
    : '<li style="color:#22c55e">No risk flags — high readiness score</li>';

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:24px;background:#f0f0f0;font-family:Arial,sans-serif">
<table width="600" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:6px;overflow:hidden;border:2px solid #CFA052;margin:auto">

  <!-- Header -->
  <tr><td style="background:#0A0F0D;padding:20px 28px">
    <table width="100%"><tr>
      <td style="color:#CFA052;font-size:16px;font-weight:bold">NEW INTAKE ALERT</td>
      <td align="right">
        <span style="background:${urgencyColor};color:#fff;font-size:10px;font-weight:bold;padding:5px 12px;border-radius:3px">${data.persona} ZONE &nbsp;·&nbsp; ${data.urgency}</span>
      </td>
    </tr></table>
  </td></tr>

  <!-- Lead details -->
  <tr><td style="padding:20px 28px">
    <table width="100%" cellpadding="0" cellspacing="0">
      <tr><td style="padding:6px 0;border-bottom:1px solid #f0f0f0">
        <span style="color:#888;font-size:11px;text-transform:uppercase">Client Name</span><br>
        <strong style="font-size:15px;color:#1A1A1A">${data.name}</strong>
      </td></tr>
      <tr><td style="padding:6px 0;border-bottom:1px solid #f0f0f0">
        <span style="color:#888;font-size:11px;text-transform:uppercase">Email</span><br>
        <a href="mailto:${data.email}" style="color:#CFA052;font-size:13px">${data.email}</a>
      </td></tr>
      <tr><td style="padding:6px 0;border-bottom:1px solid #f0f0f0">
        <span style="color:#888;font-size:11px;text-transform:uppercase">Country of Residency</span><br>
        <strong style="color:#1A1A1A">${data.country || 'Not specified'}</strong>
      </td></tr>
      <tr><td style="padding:6px 0;border-bottom:1px solid #f0f0f0">
        <span style="color:#888;font-size:11px;text-transform:uppercase">Risk Score</span><br>
        <strong style="color:${urgencyColor};font-size:16px">${data.score}/75</strong>
      </td></tr>
    </table>
  </td></tr>

  <!-- Risk flags -->
  <tr><td style="padding:0 28px 20px">
    <div style="background:#fafafa;border:1px solid #eee;border-radius:4px;padding:14px">
      <div style="font-size:11px;text-transform:uppercase;color:#888;font-weight:bold;margin-bottom:8px">Risk Flags Detected</div>
      <ul style="margin:0;padding-left:18px;font-size:12px">${flagsHtml}</ul>
    </div>
  </td></tr>

  <!-- Summary -->
  <tr><td style="padding:0 28px 24px">
    <div style="font-size:11px;text-transform:uppercase;color:#888;font-weight:bold;margin-bottom:8px">Full Assessment Summary</div>
    <div style="font-size:12px;color:#333;line-height:1.7;background:#fafafa;padding:14px;border-radius:4px;border-left:3px solid #CFA052">
      ${data.summary.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>')}
    </div>
  </td></tr>

  <!-- CTA -->
  <tr><td style="background:#0A0F0D;padding:16px 28px;text-align:center">
    <div style="color:#ccc;font-size:11px">Contact this lead within 4 hours &nbsp;·&nbsp;
      <a href="mailto:${data.email}" style="color:#CFA052">Reply to ${data.name}</a>
    </div>
  </td></tr>

</table>
</body>
</html>`;
}
